cscript

mata:
unlink("bench/test/incl_main.smcl")
unlink("bench/test/slide1.smcl")
unlink("bench/test/slide2.smcl")
unlink("bench/test/slide3.smcl")
unlink("bench/test/slide4.smcl")
unlink("bench/test/slide2ex1.do")
unlink("bench/test/slide3ex1.do")
end

smclpres using bench\incl_main.do, dir(bench/test) replace

mata:
assert(fileexists("bench/test/incl_main.smcl"))
assert(fileexists("bench/test/slide1.smcl"))
assert(fileexists("bench/test/slide2.smcl"))
assert(fileexists("bench/test/slide3.smcl"))
assert(fileexists("bench/test/slide4.smcl"))
assert(fileexists("bench/test/slide2ex1.do"))
assert(fileexists("bench/test/slide3ex1.do"))

fh = fopen(`"bench/test/incl_main.smcl"', "r")
assert(fget(fh)==`"{smcl}"')
assert(fget(fh)==`""')
assert(fget(fh)==`"{center:{bf:Including other files}}"')
assert(fget(fh)==`""')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{center:Maarten Buis}"')
assert(fget(fh)==`"{center:maarten.buis@uni.kn}"')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{* tocline }{p  4  4 2}{view slide1.smcl : section one}{p_end}"')
assert(fget(fh)==`"{* tocline }{p  8  8 2}Part one point one{p_end}"')
assert(fget(fh)==`"{* tocline }{p  8  8 2}part one point two{p_end}"')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{* tocline }{p  4  4 2}{view slide4.smcl : conclusion}{p_end}"')
assert(fget(fh)==`"{* slides }{...}"')
assert(fget(fh)==`"{* incl_main.smcl }{...}"')
assert(fget(fh)==`"{* slide1.smcl }{...}"')
assert(fget(fh)==`"{* slide2.smcl }{...}"')
assert(fget(fh)==`"{* slide3.smcl }{...}"')
assert(fget(fh)==`"{* slide4.smcl }{...}"')
assert(fget(fh)==`"{* bottomstyle arrow }{...}"')
assert(fget(fh)==J(0,0,""))
fclose(fh)


fh = fopen(`"bench/test/slide1.smcl"', "r")
assert(fget(fh)==`"{smcl}"')
assert(fget(fh)==`"{* "' + st_strscalar("c(current_date)") +`"}{...}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==`"{p}{bf:section one}{p_end}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==`""')
assert(fget(fh)==`"{center:{bf: first slide}}"')
assert(fget(fh)==`""')
assert(fget(fh)==`"{pstd}"')
assert(fget(fh)==`"Some text"')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{* ex slide1ex1 }{...}"')
assert(fget(fh)==`"{cmd}"')
assert(fget(fh)==`"        sysuse auto, clear"')
assert(fget(fh)==`"        reg price mpg"')
assert(fget(fh)==`"{txt}{...}"')
assert(fget(fh)==`"{pstd}({stata "do slide1ex1.do":{it:click to run}}){p_end}"')
assert(fget(fh)==`""')
assert(fget(fh)==`""')
assert(fget(fh)==`"{* endex }{...}"')
assert(fget(fh)==`" "')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{* /p}{hline}"')
assert(fget(fh)==`"{* bottombar }{center:     {view incl_main.smcl:index}   {view slide2.smcl:>>}}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==J(0,0,""))
fclose(fh)


fh = fopen(`"bench/test/slide2.smcl"', "r")
assert(fget(fh)==`"{smcl}"')
assert(fget(fh)==`"{* "' + st_strscalar("c(current_date)") +`"}{...}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==`"{p}{bf:section one} {hline 2} Part one point one{p_end}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==`""')
assert(fget(fh)==`"{center:{bf: Another topic}}"')
assert(fget(fh)==`""')
assert(fget(fh)==`"Some other text"')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{* ex slide2ex1 }{...}"')
assert(fget(fh)==`"{cmd}"')
assert(fget(fh)==`"        sysuse nlsw88, clear"')
assert(fget(fh)==`"        reg wage i.race i.union i.south ttl_exp"')
assert(fget(fh)==`"{txt}{...}"')
assert(fget(fh)==`"{pstd}({stata "do slide2ex1.do":{it:click to run}}){p_end}"')
assert(fget(fh)==`""')
assert(fget(fh)==`""')
assert(fget(fh)==`"{* endex }{...}"')
assert(fget(fh)==`" "')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{* /p}{hline}"')
assert(fget(fh)==`"{* bottombar }{center:{view slide1.smcl:<<}   {view incl_main.smcl:index}   {view slide3.smcl:>>}}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==J(0,0,""))
fclose(fh)

fh = fopen(`"bench/test/slide3.smcl"', "r")
assert(fget(fh)==`"{smcl}"')
assert(fget(fh)==`"{* "' + st_strscalar("c(current_date)") +`"}{...}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==`"{p}{bf:section one} {hline 2} part one point two{p_end}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==`""')
assert(fget(fh)==`"{center:{bf: blup}}"')
assert(fget(fh)==`""')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{* ex slide3ex1 }{...}"')
assert(fget(fh)==`"{cmd}"')
assert(fget(fh)==`"        sysuse cancer"')
assert(fget(fh)==`"        stcox i.drug"')
assert(fget(fh)==`"{txt}{...}"')
assert(fget(fh)==`"{pstd}({stata "do slide3ex1.do":{it:click to run}}){p_end}"')
assert(fget(fh)==`""')
assert(fget(fh)==`""')
assert(fget(fh)==`"{* endex }{...}"')
assert(fget(fh)==`" "')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{* /p}{hline}"')
assert(fget(fh)==`"{* bottombar }{center:{view slide2.smcl:<<}   {view incl_main.smcl:index}   {view slide4.smcl:>>}}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==J(0,0,""))
fclose(fh)

fh = fopen(`"bench/test/slide4.smcl"', "r")
assert(fget(fh)==`"{smcl}"')
assert(fget(fh)==`"{* "' + st_strscalar("c(current_date)") +`"}{...}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==`"{p}{bf:conclusion}{p_end}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==`""')
assert(fget(fh)==`"{center:{bf: Conclusion}}"')
assert(fget(fh)==`""')
assert(fget(fh)==`"{pstd}"')
assert(fget(fh)==`"bla bla bla"')
assert(fget(fh)==`" "')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{* /p}{hline}"')
assert(fget(fh)==`"{* bottombar }{center:{view slide3.smcl:<<}   {view incl_main.smcl:index}     }"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==J(0,0,""))
fclose(fh)

fh = fopen(`"bench/test/slide1ex1.do"', "r")
assert(fget(fh)==`"sysuse auto, clear"')
assert(fget(fh)==`"reg price mpg"')
assert(fget(fh)==J(0,0,""))
fclose(fh)

fh = fopen(`"bench/test/slide2ex1.do"', "r")
assert(fget(fh)==`"sysuse nlsw88, clear"')
assert(fget(fh)==`"reg wage i.race i.union i.south ttl_exp"')
assert(fget(fh)==J(0,0,""))
fclose(fh)

fh = fopen(`"bench/test/slide3ex1.do"', "r")
assert(fget(fh)==`"sysuse cancer"')
assert(fget(fh)==`"stcox i.drug"')
assert(fget(fh)==J(0,0,""))
fclose(fh)

unlink("bench/test/incl_main.smcl")
unlink("bench/test/slide1.smcl")
unlink("bench/test/slide2.smcl")
unlink("bench/test/slide3.smcl")
unlink("bench/test/slide4.smcl")
unlink("bench/test/slide1ex1.do")
unlink("bench/test/slide2ex1.do")
unlink("bench/test/slide3ex1.do")
end

mata:
unlink("bench/test/minimalist.smcl")
unlink("bench/test/slide1.smcl")
unlink("bench/test/slide2.smcl")
unlink("bench/test/slide3.smcl")
unlink("bench/test/slide1ex1.do")
unlink("bench/test/slide3ex1.do")
end

smclpres using bench\minimalist.do, dir(bench/test) replace

mata:
assert(fileexists("bench/test/minimalist.smcl"))
assert(fileexists("bench/test/slide1.smcl"))
assert(fileexists("bench/test/slide2.smcl"))
assert(fileexists("bench/test/slide3.smcl"))
assert(fileexists("bench/test/slide1ex1.do"))
assert(fileexists("bench/test/slide3ex1.do"))

fh = fopen(`"bench/test/minimalist.smcl"', "r")
assert(fget(fh)==`"{smcl}"')
assert(fget(fh)==`""')
assert(fget(fh)==`"{center:{bf:A minimalist example presentation}}"')
assert(fget(fh)==`""')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{center:Maarten Buis}"')
assert(fget(fh)==`"{center:maarten.buis@uni.kn}"')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{* tocline }{p  4  4 2}{view slide1.smcl : First section}{p_end}"')
assert(fget(fh)==`"{* tocline }{p  8  8 2}First subsection{p_end}"')
assert(fget(fh)==`"{* tocline }{p  8  8 2}Second subsection{p_end}"')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{* tocline }{p  4  4 2}{view slide3.smcl : Second section}{p_end}"')
assert(fget(fh)==`"{* slides }{...}"')
assert(fget(fh)==`"{* minimalist.smcl }{...}"')
assert(fget(fh)==`"{* slide1.smcl }{...}"')
assert(fget(fh)==`"{* slide2.smcl }{...}"')
assert(fget(fh)==`"{* slide3.smcl }{...}"')
assert(fget(fh)==`"{* bottomstyle label }{...}"')
assert(fget(fh)==J(0,0,""))
fclose(fh)

fh = fopen(`"bench/test/slide1.smcl"', "r")
assert(fget(fh)==`"{smcl}"')
assert(fget(fh)==`"{* "' + st_strscalar("c(current_date)") +`"}{...}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==`"{p}{bf:First section} {hline 2} First subsection{p_end}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==`""')
assert(fget(fh)==`"{center:{bf: First slide}}"')
assert(fget(fh)==`""')
assert(fget(fh)==`"{pstd}Some interesting text about {help regress}{p_end}"')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{* ex slide1ex1 }{...}"')
assert(fget(fh)==`"{cmd}"')
assert(fget(fh)==`"        sysuse auto, clear"')
assert(fget(fh)==`"        sum price"')
assert(fget(fh)==`"{txt}{...}"')
assert(fget(fh)==`"{pstd}({stata "do slide1ex1.do":{it:click to run}}){p_end}"')
assert(fget(fh)==`""')
assert(fget(fh)==`""')
assert(fget(fh)==`"{* endex }{...}"')
assert(fget(fh)==`" "')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{* /p}{hline}"')
assert(fget(fh)==`"{* bottombar }{view minimalist.smcl:index}{right:{view slide2.smcl:next}}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==J(0,0,""))
fclose(fh)

fh = fopen(`"bench/test/slide2.smcl"', "r")
assert(fget(fh)==`"{smcl}"')
assert(fget(fh)==`"{* "' + st_strscalar("c(current_date)") +`"}{...}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==`"{p}{bf:First section} {hline 2} Second subsection{p_end}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==`""')
assert(fget(fh)==`"{center:{bf: Second slide}}"')
assert(fget(fh)==`""')
assert(fget(fh)==`"{phang}Kwaak, kwaak, kikker kwaak. Als ik grote sprongen maak. Doe ik "')
assert(fget(fh)==`"net zo gek als jij, en ik kwaak er ook nog bij.{p_end}"')
assert(fget(fh)==`"{phang}Kwaak, kwaak, kwaak maar door. Kom maar in het kikker koor. "')
assert(fget(fh)==`"Kwaak van dit en kwaak van dat. Kikkers kwaken altijd wat.{p_end}"')
assert(fget(fh)==`" "')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{* /p}{hline}"')
assert(fget(fh)==`"{* bottombar }{view minimalist.smcl:index}{right:{view slide3.smcl:next}}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==J(0,0,""))
fclose(fh)

fh = fopen(`"bench/test/slide3.smcl"', "r")
assert(fget(fh)==`"{smcl}"')
assert(fget(fh)==`"{* "' + st_strscalar("c(current_date)") +`"}{...}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==`"{p}{bf:Second section}{p_end}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==`""')
assert(fget(fh)==`"{center:{bf: Third slide}}"')
assert(fget(fh)==`""')
assert(fget(fh)==`"{phang}"')
assert(fget(fh)==`"Ia zegt het ezeltje, klim maar op mijn rug. Ik draag jou de hele weg, heen"')
assert(fget(fh)==`"end weer terug."')
assert(fget(fh)==`""')
assert(fget(fh)==`"{phang}"')
assert(fget(fh)==`"Ia zegt het ezeltje. Ik loop van hier naar daar, en als je met me mee "')
assert(fget(fh)==`"wil hoor ik graag, ia ia."')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{* ex slide3ex1 }{...}"')
assert(fget(fh)==`"{cmd}"')
assert(fget(fh)==`"        reg price i.rep78 "')
assert(fget(fh)==`"{txt}{...}"')
assert(fget(fh)==`"{pstd}({stata "do slide3ex1.do":{it:click to run}}){p_end}"')
assert(fget(fh)==`""')
assert(fget(fh)==`""')
assert(fget(fh)==`"{* endex }{...}"')
assert(fget(fh)==`" "')
assert(fget(fh)==`" "')
assert(fget(fh)==`"{* /p}{hline}"')
assert(fget(fh)==`"{* bottombar }{view minimalist.smcl:index}"')
assert(fget(fh)==`"{hline}"')
assert(fget(fh)==J(0,0,""))
fclose(fh)

fh = fopen(`"bench/test/slide1ex1.do"', "r")
assert(fget(fh)==`"sysuse auto, clear"')
assert(fget(fh)==`"sum price"')
assert(fget(fh)==J(0,0,""))
fclose(fh)

fh = fopen(`"bench/test/slide3ex1.do"', "r")
assert(fget(fh)==`"reg price i.rep78 "')
assert(fget(fh)==J(0,0,""))
fclose(fh)

unlink("bench/test/minimalist.smcl")
unlink("bench/test/slide1.smcl")
unlink("bench/test/slide2.smcl")
unlink("bench/test/slide3.smcl")
unlink("bench/test/slide1ex1.do")
unlink("bench/test/slide3ex1.do")
end
